AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Game Session Management Service

Resources:
  GameSessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
        - AttributeName: hostname
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: HostnameIndex
          KeySchema:
            - AttributeName: hostname
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

  CreateGameSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/create-game-session.createGameSessionHandler
      Runtime: nodejs18.x
      Environment:
        Variables:
          TABLE_NAME: !Ref GameSessionTable
      Description: Creates a new game session.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GameSessionTable
      Events:
        CreateSession:
          Type: Api
          Properties:
            Path: /sessions
            Method: POST

  ListGameSessionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/list-game-sessions.listGameSessionsHandler
      Runtime: nodejs18.x
      Description: Creates a new game session.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GameSessionTable
      Environment:
        Variables:
          TABLE_NAME: !Ref GameSessionTable
      Events:
        ListSessions:
          Type: Api
          Properties:
            Path: /sessions
            Method: GET
Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
